<?php
function ds_superescuela()
{
	return array(
		'label' => t('Superescuela'),
		'regions' => array(
			'r1c1' => t('Row 1 Col 1'),
			'r2c1' => t('Row 2 Col 1'),
			'r2c2' => t('Row 2 Col 2'),
			'r3c1' => t('Row 3 Col 1'),
			'r3c2' => t('Row 3 Col 2'),
      'r3c3' => t('Row 3 Col 3'),
      'r3c4' => t('Row 3 Col 4'),

			'r4c1' => t('Row 4 Col 1'),
			'r5c1' => t('Row 5 Col 1'),
			'r5c2' => t('Row 5 Col 2'),
			'r6c1' => t('Row 6 Col 1'),
			'r6c2' => t('Row 6 Col 2'),
			'r6c3' => t('Row 6 Col 3'),
			
			'r7c1' => t('Row 7 Col 1'),
			'r8c1' => t('Row 8 Col 1'),
			'r8c2' => t('Row 8 Col 2'),
			'r9c1' => t('Row 9 Col 1'),
			'r9c2' => t('Row 9 Col 2'),
			'r9c3' => t('Row 9 Col 3'),
			
			'r10c1' => t('Row 10 Col 1'),
			'r11c1' => t('Row 11 Col 1'),
			'r11c2' => t('Row 11 Col 2'),
			'r12c1' => t('Row 12 Col 1'),
			'r12c2' => t('Row 12 Col 2'),
			'r12c3' => t('Row 12 Col 3'),
		),
		
		// Add this line if there is a default css file.
		'css' => true,
		
		// Add this line if you're using DS 2.x for icon preview
		'image' => false,
	);
}